#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="PortalVSL")]
public partial class FVSL_LINQDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertODS_ODS(ODS_ODS instance);
  partial void UpdateODS_ODS(ODS_ODS instance);
  partial void DeleteODS_ODS(ODS_ODS instance);
  partial void Insertbeneficiario(beneficiario instance);
  partial void Updatebeneficiario(beneficiario instance);
  partial void Deletebeneficiario(beneficiario instance);
  partial void Insertods_beneficiario(ods_beneficiario instance);
  partial void Updateods_beneficiario(ods_beneficiario instance);
  partial void Deleteods_beneficiario(ods_beneficiario instance);
  #endregion
	
	public FVSL_LINQDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PortalVSLConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public FVSL_LINQDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FVSL_LINQDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FVSL_LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FVSL_LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ODS_ODS> ODS_ODS
	{
		get
		{
			return this.GetTable<ODS_ODS>();
		}
	}
	
	public System.Data.Linq.Table<beneficiario> beneficiarios
	{
		get
		{
			return this.GetTable<beneficiario>();
		}
	}
	
	public System.Data.Linq.Table<ods_beneficiario> ods_beneficiarios
	{
		get
		{
			return this.GetTable<ods_beneficiario>();
		}
	}
	
	[Function(Name="dbo.MAPA_ODS_DETAILS")]
	public ISingleResult<ODS_ODS> MAPA_ODS_DETAILS([Parameter(DbType="Int")] System.Nullable<int> id_in)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_in);
		return ((ISingleResult<ODS_ODS>)(result.ReturnValue));
	}
	
	[Function(Name="dbo.MAPA_GET_BENF_ODS")]
	public ISingleResult<beneficiario> MAPA_GET_BENF_ODS([Parameter(DbType="Int")] System.Nullable<int> id_ods)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_ods);
		return ((ISingleResult<beneficiario>)(result.ReturnValue));
	}
}

[Table(Name="dbo.ODS_ODS")]
public partial class ODS_ODS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_ods;
	
	private string _nombre;
	
	private string _siglas;
	
	private string _rif;
	
	private bool _gubernamental;
	
	private int _figura_juridica;
	
	private int _tipo_red;
	
	private string _red_especificacion;
	
	private string _especificacion2;
	
	private System.Nullable<int> _id_OrganiSegundoPiso;
	
	private string _objetivos;
	
	private string _actividades;
	
	private System.DateTime _fecha_constitucion;
	
	private int _experiencia;
	
	private string _pagina_web;
	
	private string _email;
	
	private string _FacebookODS;
	
	private string _TwitterODS;
	
	private string _LinkedInODS;
	
	private string _MySpaceODS;
	
	private bool _sede_principal;
	
	private System.Nullable<int> _sedes;
	
	private short _TipoSede;
	
	private string _representante_nombre;
	
	private string _representante_apellido;
	
	private string _representante_cargo;
	
	private string _representante_telefono;
	
	private string _representante_correo;
	
	private string _representante_celular;
	
	private string _representante_fax;
	
	private int _id_pais;
	
	private int _id_estado;
	
	private int _id_municipio;
	
	private int _id_parroquia;
	
	private string _ciudad;
	
	private string _urbanizacion;
	
	private string _calle;
	
	private string _casa;
	
	private string _piso;
	
	private int _codigo_postal;
	
	private string _Latitud;
	
	private string _Longitud;
	
	private System.Nullable<bool> _capacitacion;
	
	private System.Nullable<bool> _especifica;
	
	private System.Nullable<bool> _inespecifica;
	
	private System.Nullable<bool> _adec_insc_consj_est;
	
	private System.Nullable<bool> _adec_insc_consj_mun;
	
	private System.Nullable<bool> _adec_insc_consj_nac;
	
	private System.Nullable<bool> _adec_recib_apoyo_concj;
	
	private System.Nullable<bool> _adec_recib_apoyo_fondo;
	
	private System.Nullable<bool> _OrganizaEstrategia;
	
	private System.Nullable<bool> _OrganizacionCuenta;
	
	private System.Nullable<bool> _centro_abrigo;
	
	private System.Nullable<int> _centro_abrigo_no_definido;
	
	private System.Nullable<int> _centro_abrigo_escolarizado;
	
	private System.Nullable<int> _centro_abrigo_adoptados;
	
	private System.Nullable<int> _centro_abrigo_adotables;
	
	private int _status;
	
	private System.DateTime _fecha_inicio_registro;
	
	private System.DateTime _fecha_fin_registro;
	
	private System.Data.Linq.Binary _Logo;
	
	private string _Telefono;
	
	private System.Nullable<int> _Usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_odsChanging(int value);
    partial void Onid_odsChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnsiglasChanging(string value);
    partial void OnsiglasChanged();
    partial void OnrifChanging(string value);
    partial void OnrifChanged();
    partial void OngubernamentalChanging(bool value);
    partial void OngubernamentalChanged();
    partial void Onfigura_juridicaChanging(int value);
    partial void Onfigura_juridicaChanged();
    partial void Ontipo_redChanging(int value);
    partial void Ontipo_redChanged();
    partial void Onred_especificacionChanging(string value);
    partial void Onred_especificacionChanged();
    partial void Onespecificacion2Changing(string value);
    partial void Onespecificacion2Changed();
    partial void Onid_OrganiSegundoPisoChanging(System.Nullable<int> value);
    partial void Onid_OrganiSegundoPisoChanged();
    partial void OnobjetivosChanging(string value);
    partial void OnobjetivosChanged();
    partial void OnactividadesChanging(string value);
    partial void OnactividadesChanged();
    partial void Onfecha_constitucionChanging(System.DateTime value);
    partial void Onfecha_constitucionChanged();
    partial void OnexperienciaChanging(int value);
    partial void OnexperienciaChanged();
    partial void Onpagina_webChanging(string value);
    partial void Onpagina_webChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnFacebookODSChanging(string value);
    partial void OnFacebookODSChanged();
    partial void OnTwitterODSChanging(string value);
    partial void OnTwitterODSChanged();
    partial void OnLinkedInODSChanging(string value);
    partial void OnLinkedInODSChanged();
    partial void OnMySpaceODSChanging(string value);
    partial void OnMySpaceODSChanged();
    partial void Onsede_principalChanging(bool value);
    partial void Onsede_principalChanged();
    partial void OnsedesChanging(System.Nullable<int> value);
    partial void OnsedesChanged();
    partial void OnTipoSedeChanging(short value);
    partial void OnTipoSedeChanged();
    partial void Onrepresentante_nombreChanging(string value);
    partial void Onrepresentante_nombreChanged();
    partial void Onrepresentante_apellidoChanging(string value);
    partial void Onrepresentante_apellidoChanged();
    partial void Onrepresentante_cargoChanging(string value);
    partial void Onrepresentante_cargoChanged();
    partial void Onrepresentante_telefonoChanging(string value);
    partial void Onrepresentante_telefonoChanged();
    partial void Onrepresentante_correoChanging(string value);
    partial void Onrepresentante_correoChanged();
    partial void Onrepresentante_celularChanging(string value);
    partial void Onrepresentante_celularChanged();
    partial void Onrepresentante_faxChanging(string value);
    partial void Onrepresentante_faxChanged();
    partial void Onid_paisChanging(int value);
    partial void Onid_paisChanged();
    partial void Onid_estadoChanging(int value);
    partial void Onid_estadoChanged();
    partial void Onid_municipioChanging(int value);
    partial void Onid_municipioChanged();
    partial void Onid_parroquiaChanging(int value);
    partial void Onid_parroquiaChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OnurbanizacionChanging(string value);
    partial void OnurbanizacionChanged();
    partial void OncalleChanging(string value);
    partial void OncalleChanged();
    partial void OncasaChanging(string value);
    partial void OncasaChanged();
    partial void OnpisoChanging(string value);
    partial void OnpisoChanged();
    partial void Oncodigo_postalChanging(int value);
    partial void Oncodigo_postalChanged();
    partial void OnLatitudChanging(string value);
    partial void OnLatitudChanged();
    partial void OnLongitudChanging(string value);
    partial void OnLongitudChanged();
    partial void OncapacitacionChanging(System.Nullable<bool> value);
    partial void OncapacitacionChanged();
    partial void OnespecificaChanging(System.Nullable<bool> value);
    partial void OnespecificaChanged();
    partial void OninespecificaChanging(System.Nullable<bool> value);
    partial void OninespecificaChanged();
    partial void Onadec_insc_consj_estChanging(System.Nullable<bool> value);
    partial void Onadec_insc_consj_estChanged();
    partial void Onadec_insc_consj_munChanging(System.Nullable<bool> value);
    partial void Onadec_insc_consj_munChanged();
    partial void Onadec_insc_consj_nacChanging(System.Nullable<bool> value);
    partial void Onadec_insc_consj_nacChanged();
    partial void Onadec_recib_apoyo_concjChanging(System.Nullable<bool> value);
    partial void Onadec_recib_apoyo_concjChanged();
    partial void Onadec_recib_apoyo_fondoChanging(System.Nullable<bool> value);
    partial void Onadec_recib_apoyo_fondoChanged();
    partial void OnOrganizaEstrategiaChanging(System.Nullable<bool> value);
    partial void OnOrganizaEstrategiaChanged();
    partial void OnOrganizacionCuentaChanging(System.Nullable<bool> value);
    partial void OnOrganizacionCuentaChanged();
    partial void Oncentro_abrigoChanging(System.Nullable<bool> value);
    partial void Oncentro_abrigoChanged();
    partial void Oncentro_abrigo_no_definidoChanging(System.Nullable<int> value);
    partial void Oncentro_abrigo_no_definidoChanged();
    partial void Oncentro_abrigo_escolarizadoChanging(System.Nullable<int> value);
    partial void Oncentro_abrigo_escolarizadoChanged();
    partial void Oncentro_abrigo_adoptadosChanging(System.Nullable<int> value);
    partial void Oncentro_abrigo_adoptadosChanged();
    partial void Oncentro_abrigo_adotablesChanging(System.Nullable<int> value);
    partial void Oncentro_abrigo_adotablesChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void Onfecha_inicio_registroChanging(System.DateTime value);
    partial void Onfecha_inicio_registroChanged();
    partial void Onfecha_fin_registroChanging(System.DateTime value);
    partial void Onfecha_fin_registroChanged();
    partial void OnLogoChanging(System.Data.Linq.Binary value);
    partial void OnLogoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnUsuarioChanging(System.Nullable<int> value);
    partial void OnUsuarioChanged();
    #endregion
	
	public ODS_ODS()
	{
		OnCreated();
	}
	
	[Column(Storage="_id_ods", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_ods
	{
		get
		{
			return this._id_ods;
		}
		set
		{
			if ((this._id_ods != value))
			{
				this.Onid_odsChanging(value);
				this.SendPropertyChanging();
				this._id_ods = value;
				this.SendPropertyChanged("id_ods");
				this.Onid_odsChanged();
			}
		}
	}
	
	[Column(Storage="_nombre", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[Column(Storage="_siglas", DbType="VarChar(100)")]
	public string siglas
	{
		get
		{
			return this._siglas;
		}
		set
		{
			if ((this._siglas != value))
			{
				this.OnsiglasChanging(value);
				this.SendPropertyChanging();
				this._siglas = value;
				this.SendPropertyChanged("siglas");
				this.OnsiglasChanged();
			}
		}
	}
	
	[Column(Storage="_rif", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string rif
	{
		get
		{
			return this._rif;
		}
		set
		{
			if ((this._rif != value))
			{
				this.OnrifChanging(value);
				this.SendPropertyChanging();
				this._rif = value;
				this.SendPropertyChanged("rif");
				this.OnrifChanged();
			}
		}
	}
	
	[Column(Storage="_gubernamental", DbType="Bit NOT NULL")]
	public bool gubernamental
	{
		get
		{
			return this._gubernamental;
		}
		set
		{
			if ((this._gubernamental != value))
			{
				this.OngubernamentalChanging(value);
				this.SendPropertyChanging();
				this._gubernamental = value;
				this.SendPropertyChanged("gubernamental");
				this.OngubernamentalChanged();
			}
		}
	}
	
	[Column(Storage="_figura_juridica", DbType="Int NOT NULL")]
	public int figura_juridica
	{
		get
		{
			return this._figura_juridica;
		}
		set
		{
			if ((this._figura_juridica != value))
			{
				this.Onfigura_juridicaChanging(value);
				this.SendPropertyChanging();
				this._figura_juridica = value;
				this.SendPropertyChanged("figura_juridica");
				this.Onfigura_juridicaChanged();
			}
		}
	}
	
	[Column(Storage="_tipo_red", DbType="Int NOT NULL")]
	public int tipo_red
	{
		get
		{
			return this._tipo_red;
		}
		set
		{
			if ((this._tipo_red != value))
			{
				this.Ontipo_redChanging(value);
				this.SendPropertyChanging();
				this._tipo_red = value;
				this.SendPropertyChanged("tipo_red");
				this.Ontipo_redChanged();
			}
		}
	}
	
	[Column(Storage="_red_especificacion", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
	public string red_especificacion
	{
		get
		{
			return this._red_especificacion;
		}
		set
		{
			if ((this._red_especificacion != value))
			{
				this.Onred_especificacionChanging(value);
				this.SendPropertyChanging();
				this._red_especificacion = value;
				this.SendPropertyChanged("red_especificacion");
				this.Onred_especificacionChanged();
			}
		}
	}
	
	[Column(Storage="_especificacion2", DbType="VarChar(1024)")]
	public string especificacion2
	{
		get
		{
			return this._especificacion2;
		}
		set
		{
			if ((this._especificacion2 != value))
			{
				this.Onespecificacion2Changing(value);
				this.SendPropertyChanging();
				this._especificacion2 = value;
				this.SendPropertyChanged("especificacion2");
				this.Onespecificacion2Changed();
			}
		}
	}
	
	[Column(Storage="_id_OrganiSegundoPiso", DbType="Int")]
	public System.Nullable<int> id_OrganiSegundoPiso
	{
		get
		{
			return this._id_OrganiSegundoPiso;
		}
		set
		{
			if ((this._id_OrganiSegundoPiso != value))
			{
				this.Onid_OrganiSegundoPisoChanging(value);
				this.SendPropertyChanging();
				this._id_OrganiSegundoPiso = value;
				this.SendPropertyChanged("id_OrganiSegundoPiso");
				this.Onid_OrganiSegundoPisoChanged();
			}
		}
	}
	
	[Column(Storage="_objetivos", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
	public string objetivos
	{
		get
		{
			return this._objetivos;
		}
		set
		{
			if ((this._objetivos != value))
			{
				this.OnobjetivosChanging(value);
				this.SendPropertyChanging();
				this._objetivos = value;
				this.SendPropertyChanged("objetivos");
				this.OnobjetivosChanged();
			}
		}
	}
	
	[Column(Storage="_actividades", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
	public string actividades
	{
		get
		{
			return this._actividades;
		}
		set
		{
			if ((this._actividades != value))
			{
				this.OnactividadesChanging(value);
				this.SendPropertyChanging();
				this._actividades = value;
				this.SendPropertyChanged("actividades");
				this.OnactividadesChanged();
			}
		}
	}
	
	[Column(Storage="_fecha_constitucion", DbType="DateTime NOT NULL")]
	public System.DateTime fecha_constitucion
	{
		get
		{
			return this._fecha_constitucion;
		}
		set
		{
			if ((this._fecha_constitucion != value))
			{
				this.Onfecha_constitucionChanging(value);
				this.SendPropertyChanging();
				this._fecha_constitucion = value;
				this.SendPropertyChanged("fecha_constitucion");
				this.Onfecha_constitucionChanged();
			}
		}
	}
	
	[Column(Storage="_experiencia", DbType="Int NOT NULL")]
	public int experiencia
	{
		get
		{
			return this._experiencia;
		}
		set
		{
			if ((this._experiencia != value))
			{
				this.OnexperienciaChanging(value);
				this.SendPropertyChanging();
				this._experiencia = value;
				this.SendPropertyChanged("experiencia");
				this.OnexperienciaChanged();
			}
		}
	}
	
	[Column(Storage="_pagina_web", DbType="VarChar(256)")]
	public string pagina_web
	{
		get
		{
			return this._pagina_web;
		}
		set
		{
			if ((this._pagina_web != value))
			{
				this.Onpagina_webChanging(value);
				this.SendPropertyChanging();
				this._pagina_web = value;
				this.SendPropertyChanged("pagina_web");
				this.Onpagina_webChanged();
			}
		}
	}
	
	[Column(Storage="_email", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[Column(Storage="_FacebookODS", DbType="VarChar(256)")]
	public string FacebookODS
	{
		get
		{
			return this._FacebookODS;
		}
		set
		{
			if ((this._FacebookODS != value))
			{
				this.OnFacebookODSChanging(value);
				this.SendPropertyChanging();
				this._FacebookODS = value;
				this.SendPropertyChanged("FacebookODS");
				this.OnFacebookODSChanged();
			}
		}
	}
	
	[Column(Storage="_TwitterODS", DbType="VarChar(256)")]
	public string TwitterODS
	{
		get
		{
			return this._TwitterODS;
		}
		set
		{
			if ((this._TwitterODS != value))
			{
				this.OnTwitterODSChanging(value);
				this.SendPropertyChanging();
				this._TwitterODS = value;
				this.SendPropertyChanged("TwitterODS");
				this.OnTwitterODSChanged();
			}
		}
	}
	
	[Column(Storage="_LinkedInODS", DbType="VarChar(256)")]
	public string LinkedInODS
	{
		get
		{
			return this._LinkedInODS;
		}
		set
		{
			if ((this._LinkedInODS != value))
			{
				this.OnLinkedInODSChanging(value);
				this.SendPropertyChanging();
				this._LinkedInODS = value;
				this.SendPropertyChanged("LinkedInODS");
				this.OnLinkedInODSChanged();
			}
		}
	}
	
	[Column(Storage="_MySpaceODS", DbType="VarChar(256)")]
	public string MySpaceODS
	{
		get
		{
			return this._MySpaceODS;
		}
		set
		{
			if ((this._MySpaceODS != value))
			{
				this.OnMySpaceODSChanging(value);
				this.SendPropertyChanging();
				this._MySpaceODS = value;
				this.SendPropertyChanged("MySpaceODS");
				this.OnMySpaceODSChanged();
			}
		}
	}
	
	[Column(Storage="_sede_principal", DbType="Bit NOT NULL")]
	public bool sede_principal
	{
		get
		{
			return this._sede_principal;
		}
		set
		{
			if ((this._sede_principal != value))
			{
				this.Onsede_principalChanging(value);
				this.SendPropertyChanging();
				this._sede_principal = value;
				this.SendPropertyChanged("sede_principal");
				this.Onsede_principalChanged();
			}
		}
	}
	
	[Column(Storage="_sedes", DbType="Int")]
	public System.Nullable<int> sedes
	{
		get
		{
			return this._sedes;
		}
		set
		{
			if ((this._sedes != value))
			{
				this.OnsedesChanging(value);
				this.SendPropertyChanging();
				this._sedes = value;
				this.SendPropertyChanged("sedes");
				this.OnsedesChanged();
			}
		}
	}
	
	[Column(Storage="_TipoSede", DbType="SmallInt NOT NULL")]
	public short TipoSede
	{
		get
		{
			return this._TipoSede;
		}
		set
		{
			if ((this._TipoSede != value))
			{
				this.OnTipoSedeChanging(value);
				this.SendPropertyChanging();
				this._TipoSede = value;
				this.SendPropertyChanged("TipoSede");
				this.OnTipoSedeChanged();
			}
		}
	}
	
	[Column(Storage="_representante_nombre", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string representante_nombre
	{
		get
		{
			return this._representante_nombre;
		}
		set
		{
			if ((this._representante_nombre != value))
			{
				this.Onrepresentante_nombreChanging(value);
				this.SendPropertyChanging();
				this._representante_nombre = value;
				this.SendPropertyChanged("representante_nombre");
				this.Onrepresentante_nombreChanged();
			}
		}
	}
	
	[Column(Storage="_representante_apellido", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string representante_apellido
	{
		get
		{
			return this._representante_apellido;
		}
		set
		{
			if ((this._representante_apellido != value))
			{
				this.Onrepresentante_apellidoChanging(value);
				this.SendPropertyChanging();
				this._representante_apellido = value;
				this.SendPropertyChanged("representante_apellido");
				this.Onrepresentante_apellidoChanged();
			}
		}
	}
	
	[Column(Storage="_representante_cargo", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string representante_cargo
	{
		get
		{
			return this._representante_cargo;
		}
		set
		{
			if ((this._representante_cargo != value))
			{
				this.Onrepresentante_cargoChanging(value);
				this.SendPropertyChanging();
				this._representante_cargo = value;
				this.SendPropertyChanged("representante_cargo");
				this.Onrepresentante_cargoChanged();
			}
		}
	}
	
	[Column(Storage="_representante_telefono", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string representante_telefono
	{
		get
		{
			return this._representante_telefono;
		}
		set
		{
			if ((this._representante_telefono != value))
			{
				this.Onrepresentante_telefonoChanging(value);
				this.SendPropertyChanging();
				this._representante_telefono = value;
				this.SendPropertyChanged("representante_telefono");
				this.Onrepresentante_telefonoChanged();
			}
		}
	}
	
	[Column(Storage="_representante_correo", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string representante_correo
	{
		get
		{
			return this._representante_correo;
		}
		set
		{
			if ((this._representante_correo != value))
			{
				this.Onrepresentante_correoChanging(value);
				this.SendPropertyChanging();
				this._representante_correo = value;
				this.SendPropertyChanged("representante_correo");
				this.Onrepresentante_correoChanged();
			}
		}
	}
	
	[Column(Storage="_representante_celular", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string representante_celular
	{
		get
		{
			return this._representante_celular;
		}
		set
		{
			if ((this._representante_celular != value))
			{
				this.Onrepresentante_celularChanging(value);
				this.SendPropertyChanging();
				this._representante_celular = value;
				this.SendPropertyChanged("representante_celular");
				this.Onrepresentante_celularChanged();
			}
		}
	}
	
	[Column(Storage="_representante_fax", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string representante_fax
	{
		get
		{
			return this._representante_fax;
		}
		set
		{
			if ((this._representante_fax != value))
			{
				this.Onrepresentante_faxChanging(value);
				this.SendPropertyChanging();
				this._representante_fax = value;
				this.SendPropertyChanged("representante_fax");
				this.Onrepresentante_faxChanged();
			}
		}
	}
	
	[Column(Storage="_id_pais", DbType="Int NOT NULL")]
	public int id_pais
	{
		get
		{
			return this._id_pais;
		}
		set
		{
			if ((this._id_pais != value))
			{
				this.Onid_paisChanging(value);
				this.SendPropertyChanging();
				this._id_pais = value;
				this.SendPropertyChanged("id_pais");
				this.Onid_paisChanged();
			}
		}
	}
	
	[Column(Storage="_id_estado", DbType="Int NOT NULL")]
	public int id_estado
	{
		get
		{
			return this._id_estado;
		}
		set
		{
			if ((this._id_estado != value))
			{
				this.Onid_estadoChanging(value);
				this.SendPropertyChanging();
				this._id_estado = value;
				this.SendPropertyChanged("id_estado");
				this.Onid_estadoChanged();
			}
		}
	}
	
	[Column(Storage="_id_municipio", DbType="Int NOT NULL")]
	public int id_municipio
	{
		get
		{
			return this._id_municipio;
		}
		set
		{
			if ((this._id_municipio != value))
			{
				this.Onid_municipioChanging(value);
				this.SendPropertyChanging();
				this._id_municipio = value;
				this.SendPropertyChanged("id_municipio");
				this.Onid_municipioChanged();
			}
		}
	}
	
	[Column(Storage="_id_parroquia", DbType="Int NOT NULL")]
	public int id_parroquia
	{
		get
		{
			return this._id_parroquia;
		}
		set
		{
			if ((this._id_parroquia != value))
			{
				this.Onid_parroquiaChanging(value);
				this.SendPropertyChanging();
				this._id_parroquia = value;
				this.SendPropertyChanged("id_parroquia");
				this.Onid_parroquiaChanged();
			}
		}
	}
	
	[Column(Storage="_ciudad", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string ciudad
	{
		get
		{
			return this._ciudad;
		}
		set
		{
			if ((this._ciudad != value))
			{
				this.OnciudadChanging(value);
				this.SendPropertyChanging();
				this._ciudad = value;
				this.SendPropertyChanged("ciudad");
				this.OnciudadChanged();
			}
		}
	}
	
	[Column(Storage="_urbanizacion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string urbanizacion
	{
		get
		{
			return this._urbanizacion;
		}
		set
		{
			if ((this._urbanizacion != value))
			{
				this.OnurbanizacionChanging(value);
				this.SendPropertyChanging();
				this._urbanizacion = value;
				this.SendPropertyChanged("urbanizacion");
				this.OnurbanizacionChanged();
			}
		}
	}
	
	[Column(Storage="_calle", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string calle
	{
		get
		{
			return this._calle;
		}
		set
		{
			if ((this._calle != value))
			{
				this.OncalleChanging(value);
				this.SendPropertyChanging();
				this._calle = value;
				this.SendPropertyChanged("calle");
				this.OncalleChanged();
			}
		}
	}
	
	[Column(Storage="_casa", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
	public string casa
	{
		get
		{
			return this._casa;
		}
		set
		{
			if ((this._casa != value))
			{
				this.OncasaChanging(value);
				this.SendPropertyChanging();
				this._casa = value;
				this.SendPropertyChanged("casa");
				this.OncasaChanged();
			}
		}
	}
	
	[Column(Storage="_piso", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string piso
	{
		get
		{
			return this._piso;
		}
		set
		{
			if ((this._piso != value))
			{
				this.OnpisoChanging(value);
				this.SendPropertyChanging();
				this._piso = value;
				this.SendPropertyChanged("piso");
				this.OnpisoChanged();
			}
		}
	}
	
	[Column(Storage="_codigo_postal", DbType="Int NOT NULL")]
	public int codigo_postal
	{
		get
		{
			return this._codigo_postal;
		}
		set
		{
			if ((this._codigo_postal != value))
			{
				this.Oncodigo_postalChanging(value);
				this.SendPropertyChanging();
				this._codigo_postal = value;
				this.SendPropertyChanged("codigo_postal");
				this.Oncodigo_postalChanged();
			}
		}
	}
	
	[Column(Storage="_Latitud", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Latitud
	{
		get
		{
			return this._Latitud;
		}
		set
		{
			if ((this._Latitud != value))
			{
				this.OnLatitudChanging(value);
				this.SendPropertyChanging();
				this._Latitud = value;
				this.SendPropertyChanged("Latitud");
				this.OnLatitudChanged();
			}
		}
	}
	
	[Column(Storage="_Longitud", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Longitud
	{
		get
		{
			return this._Longitud;
		}
		set
		{
			if ((this._Longitud != value))
			{
				this.OnLongitudChanging(value);
				this.SendPropertyChanging();
				this._Longitud = value;
				this.SendPropertyChanged("Longitud");
				this.OnLongitudChanged();
			}
		}
	}
	
	[Column(Storage="_capacitacion", DbType="Bit")]
	public System.Nullable<bool> capacitacion
	{
		get
		{
			return this._capacitacion;
		}
		set
		{
			if ((this._capacitacion != value))
			{
				this.OncapacitacionChanging(value);
				this.SendPropertyChanging();
				this._capacitacion = value;
				this.SendPropertyChanged("capacitacion");
				this.OncapacitacionChanged();
			}
		}
	}
	
	[Column(Storage="_especifica", DbType="Bit")]
	public System.Nullable<bool> especifica
	{
		get
		{
			return this._especifica;
		}
		set
		{
			if ((this._especifica != value))
			{
				this.OnespecificaChanging(value);
				this.SendPropertyChanging();
				this._especifica = value;
				this.SendPropertyChanged("especifica");
				this.OnespecificaChanged();
			}
		}
	}
	
	[Column(Storage="_inespecifica", DbType="Bit")]
	public System.Nullable<bool> inespecifica
	{
		get
		{
			return this._inespecifica;
		}
		set
		{
			if ((this._inespecifica != value))
			{
				this.OninespecificaChanging(value);
				this.SendPropertyChanging();
				this._inespecifica = value;
				this.SendPropertyChanged("inespecifica");
				this.OninespecificaChanged();
			}
		}
	}
	
	[Column(Storage="_adec_insc_consj_est", DbType="Bit")]
	public System.Nullable<bool> adec_insc_consj_est
	{
		get
		{
			return this._adec_insc_consj_est;
		}
		set
		{
			if ((this._adec_insc_consj_est != value))
			{
				this.Onadec_insc_consj_estChanging(value);
				this.SendPropertyChanging();
				this._adec_insc_consj_est = value;
				this.SendPropertyChanged("adec_insc_consj_est");
				this.Onadec_insc_consj_estChanged();
			}
		}
	}
	
	[Column(Storage="_adec_insc_consj_mun", DbType="Bit")]
	public System.Nullable<bool> adec_insc_consj_mun
	{
		get
		{
			return this._adec_insc_consj_mun;
		}
		set
		{
			if ((this._adec_insc_consj_mun != value))
			{
				this.Onadec_insc_consj_munChanging(value);
				this.SendPropertyChanging();
				this._adec_insc_consj_mun = value;
				this.SendPropertyChanged("adec_insc_consj_mun");
				this.Onadec_insc_consj_munChanged();
			}
		}
	}
	
	[Column(Storage="_adec_insc_consj_nac", DbType="Bit")]
	public System.Nullable<bool> adec_insc_consj_nac
	{
		get
		{
			return this._adec_insc_consj_nac;
		}
		set
		{
			if ((this._adec_insc_consj_nac != value))
			{
				this.Onadec_insc_consj_nacChanging(value);
				this.SendPropertyChanging();
				this._adec_insc_consj_nac = value;
				this.SendPropertyChanged("adec_insc_consj_nac");
				this.Onadec_insc_consj_nacChanged();
			}
		}
	}
	
	[Column(Storage="_adec_recib_apoyo_concj", DbType="Bit")]
	public System.Nullable<bool> adec_recib_apoyo_concj
	{
		get
		{
			return this._adec_recib_apoyo_concj;
		}
		set
		{
			if ((this._adec_recib_apoyo_concj != value))
			{
				this.Onadec_recib_apoyo_concjChanging(value);
				this.SendPropertyChanging();
				this._adec_recib_apoyo_concj = value;
				this.SendPropertyChanged("adec_recib_apoyo_concj");
				this.Onadec_recib_apoyo_concjChanged();
			}
		}
	}
	
	[Column(Storage="_adec_recib_apoyo_fondo", DbType="Bit")]
	public System.Nullable<bool> adec_recib_apoyo_fondo
	{
		get
		{
			return this._adec_recib_apoyo_fondo;
		}
		set
		{
			if ((this._adec_recib_apoyo_fondo != value))
			{
				this.Onadec_recib_apoyo_fondoChanging(value);
				this.SendPropertyChanging();
				this._adec_recib_apoyo_fondo = value;
				this.SendPropertyChanged("adec_recib_apoyo_fondo");
				this.Onadec_recib_apoyo_fondoChanged();
			}
		}
	}
	
	[Column(Storage="_OrganizaEstrategia", DbType="Bit")]
	public System.Nullable<bool> OrganizaEstrategia
	{
		get
		{
			return this._OrganizaEstrategia;
		}
		set
		{
			if ((this._OrganizaEstrategia != value))
			{
				this.OnOrganizaEstrategiaChanging(value);
				this.SendPropertyChanging();
				this._OrganizaEstrategia = value;
				this.SendPropertyChanged("OrganizaEstrategia");
				this.OnOrganizaEstrategiaChanged();
			}
		}
	}
	
	[Column(Storage="_OrganizacionCuenta", DbType="Bit")]
	public System.Nullable<bool> OrganizacionCuenta
	{
		get
		{
			return this._OrganizacionCuenta;
		}
		set
		{
			if ((this._OrganizacionCuenta != value))
			{
				this.OnOrganizacionCuentaChanging(value);
				this.SendPropertyChanging();
				this._OrganizacionCuenta = value;
				this.SendPropertyChanged("OrganizacionCuenta");
				this.OnOrganizacionCuentaChanged();
			}
		}
	}
	
	[Column(Storage="_centro_abrigo", DbType="Bit")]
	public System.Nullable<bool> centro_abrigo
	{
		get
		{
			return this._centro_abrigo;
		}
		set
		{
			if ((this._centro_abrigo != value))
			{
				this.Oncentro_abrigoChanging(value);
				this.SendPropertyChanging();
				this._centro_abrigo = value;
				this.SendPropertyChanged("centro_abrigo");
				this.Oncentro_abrigoChanged();
			}
		}
	}
	
	[Column(Storage="_centro_abrigo_no_definido", DbType="Int")]
	public System.Nullable<int> centro_abrigo_no_definido
	{
		get
		{
			return this._centro_abrigo_no_definido;
		}
		set
		{
			if ((this._centro_abrigo_no_definido != value))
			{
				this.Oncentro_abrigo_no_definidoChanging(value);
				this.SendPropertyChanging();
				this._centro_abrigo_no_definido = value;
				this.SendPropertyChanged("centro_abrigo_no_definido");
				this.Oncentro_abrigo_no_definidoChanged();
			}
		}
	}
	
	[Column(Storage="_centro_abrigo_escolarizado", DbType="Int")]
	public System.Nullable<int> centro_abrigo_escolarizado
	{
		get
		{
			return this._centro_abrigo_escolarizado;
		}
		set
		{
			if ((this._centro_abrigo_escolarizado != value))
			{
				this.Oncentro_abrigo_escolarizadoChanging(value);
				this.SendPropertyChanging();
				this._centro_abrigo_escolarizado = value;
				this.SendPropertyChanged("centro_abrigo_escolarizado");
				this.Oncentro_abrigo_escolarizadoChanged();
			}
		}
	}
	
	[Column(Storage="_centro_abrigo_adoptados", DbType="Int")]
	public System.Nullable<int> centro_abrigo_adoptados
	{
		get
		{
			return this._centro_abrigo_adoptados;
		}
		set
		{
			if ((this._centro_abrigo_adoptados != value))
			{
				this.Oncentro_abrigo_adoptadosChanging(value);
				this.SendPropertyChanging();
				this._centro_abrigo_adoptados = value;
				this.SendPropertyChanged("centro_abrigo_adoptados");
				this.Oncentro_abrigo_adoptadosChanged();
			}
		}
	}
	
	[Column(Storage="_centro_abrigo_adotables", DbType="Int")]
	public System.Nullable<int> centro_abrigo_adotables
	{
		get
		{
			return this._centro_abrigo_adotables;
		}
		set
		{
			if ((this._centro_abrigo_adotables != value))
			{
				this.Oncentro_abrigo_adotablesChanging(value);
				this.SendPropertyChanging();
				this._centro_abrigo_adotables = value;
				this.SendPropertyChanged("centro_abrigo_adotables");
				this.Oncentro_abrigo_adotablesChanged();
			}
		}
	}
	
	[Column(Storage="_status", DbType="Int NOT NULL")]
	public int status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[Column(Storage="_fecha_inicio_registro", DbType="DateTime NOT NULL")]
	public System.DateTime fecha_inicio_registro
	{
		get
		{
			return this._fecha_inicio_registro;
		}
		set
		{
			if ((this._fecha_inicio_registro != value))
			{
				this.Onfecha_inicio_registroChanging(value);
				this.SendPropertyChanging();
				this._fecha_inicio_registro = value;
				this.SendPropertyChanged("fecha_inicio_registro");
				this.Onfecha_inicio_registroChanged();
			}
		}
	}
	
	[Column(Storage="_fecha_fin_registro", DbType="DateTime NOT NULL")]
	public System.DateTime fecha_fin_registro
	{
		get
		{
			return this._fecha_fin_registro;
		}
		set
		{
			if ((this._fecha_fin_registro != value))
			{
				this.Onfecha_fin_registroChanging(value);
				this.SendPropertyChanging();
				this._fecha_fin_registro = value;
				this.SendPropertyChanged("fecha_fin_registro");
				this.Onfecha_fin_registroChanged();
			}
		}
	}
	
	[Column(Storage="_Logo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Logo
	{
		get
		{
			return this._Logo;
		}
		set
		{
			if ((this._Logo != value))
			{
				this.OnLogoChanging(value);
				this.SendPropertyChanging();
				this._Logo = value;
				this.SendPropertyChanged("Logo");
				this.OnLogoChanged();
			}
		}
	}
	
	[Column(Storage="_Telefono", DbType="VarChar(50)")]
	public string Telefono
	{
		get
		{
			return this._Telefono;
		}
		set
		{
			if ((this._Telefono != value))
			{
				this.OnTelefonoChanging(value);
				this.SendPropertyChanging();
				this._Telefono = value;
				this.SendPropertyChanged("Telefono");
				this.OnTelefonoChanged();
			}
		}
	}
	
	[Column(Storage="_Usuario", DbType="Int")]
	public System.Nullable<int> Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.beneficiario")]
public partial class beneficiario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_beneficiario;
	
	private string _nombre;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_beneficiarioChanging(int value);
    partial void Onid_beneficiarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
	
	public beneficiario()
	{
		OnCreated();
	}
	
	[Column(Storage="_id_beneficiario", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id_beneficiario
	{
		get
		{
			return this._id_beneficiario;
		}
		set
		{
			if ((this._id_beneficiario != value))
			{
				this.Onid_beneficiarioChanging(value);
				this.SendPropertyChanging();
				this._id_beneficiario = value;
				this.SendPropertyChanged("id_beneficiario");
				this.Onid_beneficiarioChanged();
			}
		}
	}
	
	[Column(Storage="_nombre", DbType="VarChar(100)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.ods_beneficiario")]
public partial class ods_beneficiario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_ods_beneficiario;
	
	private int _id_ods;
	
	private int _id_beneficiario;
	
	private int _cantidad;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ods_beneficiarioChanging(int value);
    partial void Onid_ods_beneficiarioChanged();
    partial void Onid_odsChanging(int value);
    partial void Onid_odsChanged();
    partial void Onid_beneficiarioChanging(int value);
    partial void Onid_beneficiarioChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    #endregion
	
	public ods_beneficiario()
	{
		OnCreated();
	}
	
	[Column(Storage="_id_ods_beneficiario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_ods_beneficiario
	{
		get
		{
			return this._id_ods_beneficiario;
		}
		set
		{
			if ((this._id_ods_beneficiario != value))
			{
				this.Onid_ods_beneficiarioChanging(value);
				this.SendPropertyChanging();
				this._id_ods_beneficiario = value;
				this.SendPropertyChanged("id_ods_beneficiario");
				this.Onid_ods_beneficiarioChanged();
			}
		}
	}
	
	[Column(Storage="_id_ods", DbType="Int NOT NULL")]
	public int id_ods
	{
		get
		{
			return this._id_ods;
		}
		set
		{
			if ((this._id_ods != value))
			{
				this.Onid_odsChanging(value);
				this.SendPropertyChanging();
				this._id_ods = value;
				this.SendPropertyChanged("id_ods");
				this.Onid_odsChanged();
			}
		}
	}
	
	[Column(Storage="_id_beneficiario", DbType="Int NOT NULL")]
	public int id_beneficiario
	{
		get
		{
			return this._id_beneficiario;
		}
		set
		{
			if ((this._id_beneficiario != value))
			{
				this.Onid_beneficiarioChanging(value);
				this.SendPropertyChanging();
				this._id_beneficiario = value;
				this.SendPropertyChanged("id_beneficiario");
				this.Onid_beneficiarioChanged();
			}
		}
	}
	
	[Column(Storage="_cantidad", DbType="Int NOT NULL")]
	public int cantidad
	{
		get
		{
			return this._cantidad;
		}
		set
		{
			if ((this._cantidad != value))
			{
				this.OncantidadChanging(value);
				this.SendPropertyChanging();
				this._cantidad = value;
				this.SendPropertyChanged("cantidad");
				this.OncantidadChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
